
name: CI
on: pull_request_target

jobs:
  update-lockfile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
